language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t charlymarchiaro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true charlymarchiaro/docker-react npm run test